<a href="https://colab.research.google.com/github/raja-kumar-jha/pytorch-deep-learning-journey/blob/main/notebooks/00_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamantels

## Import Important Libraries

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print(torch.__version__)

2.11.0+cpu


## Introduction to tensor
### Creating Tensors

In [3]:
# Scalar
scalar = torch.tensor(27)
scalar

tensor(27)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back to python int
scalar.item()

27

In [6]:
# Vector
vector = torch.tensor([27, 27])
vector

tensor([27, 27])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([3, 3])

In [12]:
# Tensor
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

It is telling that we got **one** `3x3 `**tensor**.






In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

Random number are important because neural network start learning with full of random numbers and then it adjust those numbers to better represent data.



`start with random numbers -> look at data -> update random number -> again look at the data -> again update the data and keep doing until get the result`



In [16]:
# Create the rendom tensor
random_tensor = torch.rand(2,3)
random_tensor

tensor([[0.1073, 0.4697, 0.4573],
        [0.0106, 0.0421, 0.8330]])

In [17]:
random_tensor.ndim

2

In [18]:
random_tensor.shape

torch.Size([2, 3])

In [19]:
# Create a random tensor with similar shape of an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # heigh, width, colour channels (R, G, B)
random_image_size_tensor

tensor([[[0.3033, 0.8352, 0.7148],
         [0.8457, 0.4777, 0.4060],
         [0.6146, 0.7578, 0.8069],
         ...,
         [0.5220, 0.6993, 0.2860],
         [0.6522, 0.3310, 0.2476],
         [0.8890, 0.4525, 0.4659]],

        [[0.7029, 0.1168, 0.6609],
         [0.1245, 0.6514, 0.8335],
         [0.9304, 0.8923, 0.0053],
         ...,
         [0.5356, 0.7978, 0.7505],
         [0.5353, 0.0621, 0.8884],
         [0.8055, 0.6698, 0.5733]],

        [[0.7869, 0.8514, 0.9847],
         [0.6695, 0.0250, 0.5688],
         [0.8961, 0.6464, 0.9098],
         ...,
         [0.6789, 0.6629, 0.4140],
         [0.5624, 0.8901, 0.0367],
         [0.4096, 0.5193, 0.9470]],

        ...,

        [[0.7892, 0.8917, 0.9410],
         [0.7956, 0.5038, 0.7573],
         [0.5257, 0.4656, 0.7921],
         ...,
         [0.9838, 0.7337, 0.6654],
         [0.5009, 0.7697, 0.0611],
         [0.3096, 0.6251, 0.2741]],

        [[0.2163, 0.0278, 0.6705],
         [0.6136, 0.9933, 0.0488],
         [0.

In [20]:
random_image_size_tensor.ndim

3

In [21]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

### Zeros and Ones

In [22]:
# create a tensor of all zeros
zeros = torch.zeros(size=(2,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# create a tensor with all ones
ones = torch.ones(size=(5,6))
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [28]:
# use torch.range()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
one_to_ten = torch.arange(start=1, end=11, step=2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [32]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor datatype

In [33]:
float_32_tensor = torch.tensor([3.0, 4.5, 5.6],
                               dtype=None,
                               )
float_32_tensor

tensor([3.0000, 4.5000, 5.6000])

In [34]:
float_32_tensor.dtype

torch.float32

In [36]:
float_64_tensor = torch.tensor([2.3, 4.9, 9.7],
                               dtype=torch.float64, # what datatype is the tensor(e.g. float64, flaot32, float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_64_tensor

tensor([2.3000, 4.9000, 9.7000], dtype=torch.float64)

In [37]:
# conversion
flaot_16_tensor = float_32_tensor.type(torch.float16)
flaot_16_tensor

tensor([3.0000, 4.5000, 5.6016], dtype=torch.float16)

### Getting information from tensors

In [38]:
X_tensor = torch.rand(3, 5)
X_tensor

tensor([[0.8865, 0.3040, 0.8365, 0.5792, 0.9131],
        [0.1022, 0.9920, 0.7947, 0.6398, 0.3792],
        [0.7591, 0.4969, 0.2760, 0.6858, 0.1531]])

In [43]:
# Find out the details about some tensor
print(f'datatype of tensor: {X_tensor.dtype}')
print(f'Shape of the tensor: {X_tensor.shape}')
print(f'Device on which the tensor is running: {X_tensor.device}')

datatype of tensor: torch.float32
Shape of the tensor: torch.Size([3, 5])
Device on which the tensor is running: cpu


`shape` and `size()` are similar.

In [44]:
X_tensor.size() == X_tensor.shape

True

### Manipulating Tensors (tensors Opertaions)

Tensors Operations:
* Addition
* Substraction
* Multiplication(Element-wise)
* Division
* Matrix Multipication

In [46]:
# Create a tensor and add 101
tensor = torch.tensor([1, 2, 3])
tensor + 101

tensor([102, 103, 104])

In [54]:
torch.add(tensor, 101)

tensor([102, 103, 104])

In [48]:
# Substarct 10 from tensor
tensor - 12

tensor([-11, -10,  -9])

In [51]:
# Multiply tensor by 10\
tensor * 10

tensor([10, 20, 30])

In [53]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [58]:
# divide tensor by 10
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [59]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])