<a href="https://colab.research.google.com/github/raja-kumar-jha/pytorch-deep-learning-journey/blob/main/notebooks/00_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamantels

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print(torch.__version__)

2.11.0+cu128


## Introduction to tensor
### Creating Tensors

In [2]:
# Scalar
scalar = torch.tensor(27)
scalar

tensor(27)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back to python int
scalar.item()

27

In [5]:
# Vector
vector = torch.tensor([27, 27])
vector

tensor([27, 27])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([3, 3])

In [11]:
# Tensor
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

It is telling that we got **one** `3x3 `**tensor**.






In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

Random number are important because neural network start learning with full of random numbers and then it adjust those numbers to better represent data.



`start with random numbers -> look at data -> update random number -> again look at the data -> again update the data and keep doing until get the result`



In [15]:
# Create the rendom tensor
random_tensor = torch.rand(2,3)
random_tensor

tensor([[0.6506, 0.3386, 0.3857],
        [0.1404, 0.3993, 0.7234]])

In [16]:
random_tensor.ndim

2

In [17]:
random_tensor.shape

torch.Size([2, 3])

In [18]:
# Create a random tensor with similar shape of an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # heigh, width, colour channels (R, G, B)
random_image_size_tensor

tensor([[[0.7698, 0.9668, 0.3424],
         [0.3321, 0.5143, 0.4152],
         [0.1204, 0.8095, 0.4026],
         ...,
         [0.1031, 0.4894, 0.4242],
         [0.7009, 0.8591, 0.9940],
         [0.6260, 0.2997, 0.2720]],

        [[0.2787, 0.9739, 0.3510],
         [0.0219, 0.6660, 0.7368],
         [0.4371, 0.8855, 0.5087],
         ...,
         [0.4954, 0.2512, 0.9138],
         [0.9025, 0.8083, 0.1993],
         [0.9232, 0.6749, 0.6992]],

        [[0.2585, 0.9321, 0.2309],
         [0.5680, 0.9009, 0.8186],
         [0.1420, 0.0928, 0.8278],
         ...,
         [0.0567, 0.5518, 0.7478],
         [0.6666, 0.8854, 0.9266],
         [0.3030, 0.3170, 0.4185]],

        ...,

        [[0.6525, 0.0296, 0.6313],
         [0.9779, 0.1919, 0.8869],
         [0.5937, 0.7268, 0.4595],
         ...,
         [0.0187, 0.2374, 0.3240],
         [0.9566, 0.2472, 0.2611],
         [0.6597, 0.0524, 0.4511]],

        [[0.9990, 0.7736, 0.7660],
         [0.7379, 0.6781, 0.5131],
         [0.

In [19]:
random_image_size_tensor.ndim

3

In [20]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

### Zeros and Ones

In [21]:
# create a tensor of all zeros
zeros = torch.zeros(size=(2,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# create a tensor with all ones
ones = torch.ones(size=(5,6))
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [24]:
# use torch.range()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
one_to_ten = torch.arange(start=1, end=11, step=2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [26]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor datatype

In [27]:
float_32_tensor = torch.tensor([3.0, 4.5, 5.6],
                               dtype=None,
                               )
float_32_tensor

tensor([3.0000, 4.5000, 5.6000])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_64_tensor = torch.tensor([2.3, 4.9, 9.7],
                               dtype=torch.float64, # what datatype is the tensor(e.g. float64, flaot32, float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_64_tensor

tensor([2.3000, 4.9000, 9.7000], dtype=torch.float64)

In [30]:
# conversion
flaot_16_tensor = float_32_tensor.type(torch.float16)
flaot_16_tensor

tensor([3.0000, 4.5000, 5.6016], dtype=torch.float16)

### Getting information from tensors

In [31]:
X_tensor = torch.rand(3, 5)
X_tensor

tensor([[0.7265, 0.1858, 0.3611, 0.0632, 0.7421],
        [0.5592, 0.6920, 0.6714, 0.1330, 0.1166],
        [0.5709, 0.8436, 0.3563, 0.0941, 0.1927]])

In [32]:
# Find out the details about some tensor
print(f'datatype of tensor: {X_tensor.dtype}')
print(f'Shape of the tensor: {X_tensor.shape}')
print(f'Device on which the tensor is running: {X_tensor.device}')

datatype of tensor: torch.float32
Shape of the tensor: torch.Size([3, 5])
Device on which the tensor is running: cpu


`shape` and `size()` are similar.

In [33]:
X_tensor.size() == X_tensor.shape

True

### Manipulating Tensors (tensors Opertaions)

Tensors Operations:
* Addition
* Substraction
* Multiplication(Element-wise)
* Division
* Matrix Multipication

In [34]:
# Create a tensor and add 101
tensor = torch.tensor([1, 2, 3])
tensor + 101

tensor([102, 103, 104])

In [35]:
torch.add(tensor, 101)

tensor([102, 103, 104])

In [36]:
# Substarct 10 from tensor
tensor - 12

tensor([-11, -10,  -9])

In [37]:
# Multiply tensor by 10\
tensor * 10

tensor([10, 20, 30])

In [38]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [39]:
# divide tensor by 10
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [40]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

### Matrix multiplication

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [41]:
# Element wise multiplication
print(tensor * tensor)

tensor([1, 4, 9])


In [42]:
# Matrix multiplication
print(tensor, '*', tensor)
torch.matmul(tensor, tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])


tensor(14)

In [43]:
X_1 = torch.tensor([[1, 2, 3],
                    [5, 6, 8],
                    [8, 9, 10]])
print(X_1)

Y_1 = torch.tensor([[10, 11, 13],
                    [14, 15, 16],
                    [18, 19, 20]])
print(Y_1)

XY = X_1 * Y_1


tensor([[ 1,  2,  3],
        [ 5,  6,  8],
        [ 8,  9, 10]])
tensor([[10, 11, 13],
        [14, 15, 16],
        [18, 19, 20]])


In [44]:
XY

tensor([[ 10,  22,  39],
        [ 70,  90, 128],
        [144, 171, 200]])

In [45]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.13 ms, sys: 0 ns, total: 1.13 ms
Wall time: 2.4 ms


In [46]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 275 µs, sys: 28 µs, total: 303 µs
Wall time: 342 µs


tensor(14)

In [47]:
# @ this is use for matrix multiplication
%%time
torch.rand(3, 4)@torch.rand(4, 5)

CPU times: user 1.35 ms, sys: 34 µs, total: 1.38 ms
Wall time: 14.2 ms


tensor([[0.7148, 0.5307, 1.4031, 1.2434, 0.8860],
        [0.9393, 1.0360, 0.7520, 1.2760, 0.6561],
        [1.4145, 1.1955, 0.8541, 2.0193, 0.7403]])

In [48]:
torch.matmul(torch.rand(1, 5), torch.rand(5, 2)).shape

torch.Size([1, 2])

### One of the most common errors in deep learning: Shape errors

In [49]:
# shape for multiplication
tensor_A = torch.tensor([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]])

tensor_B = torch.tensor([[2, 4, 6],
                         [2, 5, 7],
                         [6, 8, 9]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writting less code)

tensor([[ 24,  38,  47],
        [ 54,  89, 113],
        [ 84, 140, 179]])

In [50]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 3]), torch.Size([3, 3]))

### Rule of multiplication
The **column** of **first matrix** should be **equal** to the `row` of **second matrix**.  
e.g ->
*   `(2, 3)` @ `(2, 3)` -> Can't be multiplied
*   `(2, 3)` @ `(3, 4)` -> will give result matrix of `(2, 4)`

To fix the shape issue we can use **TRANSPOSE** method.



In [51]:
# For Example
tensor_C = torch.rand(1, 2)

tensor_D = torch.rand(1, 2)

tensor_C.shape, tensor_D.shape

(torch.Size([1, 2]), torch.Size([1, 2]))

In [53]:
# if we multiply there two above tensors we will get the error
tensor_C@tensor_D

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x2 and 1x2)

In [ ]:
# To fix this error now we gonna use transpose(T)
tensor_D.T.shape # T is use to transope

In [54]:
# Now we got the correct shape for matix multiplcation
tensor_C@tensor_D.T

tensor([[1.0171]])

## Finding the `min`, `max`, `sum`, etc (tensor aggregation)

In [55]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
# finding the min
x.min()

tensor(0)

In [57]:
torch.min(x)

tensor(0)

In [58]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [105]:
# Find the mean
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [106]:
x.dtype

torch.int64

To fix this error we have to change the datatype of the tensor x. because x is int64 which is not allowed for this particular operation

In [107]:
torch.mean(x.type(torch.float64))

tensor(4., dtype=torch.float64)

In [108]:
x.type(torch.float64).mean()

tensor(4., dtype=torch.float64)

In [109]:
# find the sum
torch.sum(x), x.sum()

(tensor(36), tensor(36))

## Finding the positonal min and max

In [110]:
x

tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])

In [111]:
# find the positon in tensor that has minimum value with argmin()
x.argmin()

tensor(0)

In [112]:
# find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(8)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input to a defind shape
* View - Return a view of an input tensor of certain shape but keep the same memory as original ltensor
* Stacking - combining multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [113]:
# Create a tensor
y = torch.arange(1., 10.)

y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [114]:
# Add an extra dimension
y_reshaped = y.reshape(3, 3)
y_reshaped, y_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [115]:
# Create a view
z = y.view(1, 9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [116]:
# changing z changes y (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 12
z, y

(tensor([[12.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([12.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [117]:
# Stack tensor on top of each other
y_stacked = torch.stack([y, y, y, y], dim=0)
y_stacked

tensor([[12.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [12.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [12.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [12.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [118]:
# torch.squeeze() - removes all the single dimensions from target tensor
y_reshaped

tensor([[12.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]])

In [119]:
y_reshaped.shape

torch.Size([3, 3])

In [120]:
y_reshaped.squeeze()

tensor([[12.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]])

In [121]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [122]:
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [123]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [124]:
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [125]:
y = torch.squeeze(x, 0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [126]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [127]:
y = torch.squeeze(x, (1, 2, 3))
y.shape

torch.Size([2, 2, 2])

In [128]:
# torch.unsqueez() - adds a single dimension to a target tensor at a specific dim
A_tensor = torch.arange(1, 10)
A_tensor, A_tensor.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [129]:
A_tensor_squeezed = torch.squeeze(x)
A_tensor_squeezed.shape

torch.Size([2, 2, 2])

In [130]:
A_tensor_squeezed

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [131]:
A_tensor_unsqueezed = A_tensor_squeezed.unsqueeze(dim=1)
A_tensor_unsqueezed.shape

torch.Size([2, 1, 2, 2])

In [132]:
# torch.permute - rearranges the dimensions of target tensor in a spacific order
x_original = torch.rand(size = (224, 224, 3)) # [height, width, and colour_channel]
x_original.shape

torch.Size([224, 224, 3])

In [133]:
# Permute the origin tensor to rearrange the asix (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shift colour_channel to 1st, then height and at the end width [these 2, 0 and 1 is basically the index of it]
x_permuted.shape

torch.Size([3, 224, 224])

In [134]:
x_original[0, 0, 0] = 121
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(121.), tensor(121.))

## Indexing (selecting data from tensors)

In [135]:
# Create a tensor
x = torch.arange(0, 9).reshape(1, 3, 3)
x, x.shape

(tensor([[[0, 1, 2],
          [3, 4, 5],
          [6, 7, 8]]]),
 torch.Size([1, 3, 3]))

In [136]:
# let's index on our new tensor
x[0]

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [137]:
x[0][0], x[0, 0]

(tensor([0, 1, 2]), tensor([0, 1, 2]))

In [138]:
x[0, 1, 1]

tensor(4)

In [139]:
x[0, 2, 2]
# This is our last element

tensor(8)

In [140]:
# we can also use ":" to select all of a target dimension
x[:, 0]

tensor([[0, 1, 2]])

In [141]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[1, 4, 7]])

## PyTorch and NumPy

NumPy is a popular scientific Python numerical computing library. And because of it, PyTorch has functionality to interect with it.

* Data in NumPy -> PyTorch -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> t`orch.tensor.numpy()`


In [142]:
# NumPy array to tensor
array = np.arange(1.0, 10.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [143]:
# tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## PyTorch reproducibility (trying to take random out of random)
In short how a neural network learns:
`start with random number -> tensor operation -> update random numbers to try and make better representations of the data -> again -> again`

To reduce the randomness in neural network and pytorch comes the concept called **random seed**

Essentially what the random seed does is "flavor" the randomness.

In [144]:
# create two random tensor
random_tensor_A = torch.rand(3, 4)

random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2933, 0.5889, 0.4117, 0.0992],
        [0.3078, 0.7786, 0.8016, 0.3649],
        [0.6286, 0.9663, 0.7687, 0.4566]])
tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [145]:
# lets make some random but reproducible tensor

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs for faster computation

GPUs = faster computation on numbers, thaks to CUDA And NVIDIA hardware + PyTorch working behind :)

In [146]:
!nvidia-smi

Thu Aug  6 20:29:22 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   46C    P0             26W /   70W |     107MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 1. check for gpu access with PyTorch


In [147]:
# check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [148]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [149]:
# count number of device
torch.cuda.device_count()

1

### 2. Putting tensors(and models ) on the GPU

the reason we want our tensors/models on gpu is because using the GPUs, our results will be faster

In [150]:
# Create a tensor(default on the cpu)
tensor = torch.tensor([1, 2, 3])

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [151]:
# Move tensor to GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 3. Moving tensor back to the cpu

In [153]:
# if tensor is on gpu, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [154]:
# To fix the GPU tendor with NumPy issue, we can first set it to the CPU
tensor_back_to_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_to_cpu

array([1, 2, 3])