<a href="https://colab.research.google.com/github/raja-kumar-jha/pytorch-deep-learning-journey/blob/main/notebooks/00_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamantels

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print(torch.__version__)

2.11.0+cpu


## Introduction to tensor
### Creating Tensors

In [2]:
# Scalar
scalar = torch.tensor(27)
scalar

tensor(27)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back to python int
scalar.item()

27

In [5]:
# Vector
vector = torch.tensor([27, 27])
vector

tensor([27, 27])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([3, 3])

In [11]:
# Tensor
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

It is telling that we got **one** `3x3 `**tensor**.






In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

Random number are important because neural network start learning with full of random numbers and then it adjust those numbers to better represent data.



`start with random numbers -> look at data -> update random number -> again look at the data -> again update the data and keep doing until get the result`



In [15]:
# Create the rendom tensor
random_tensor = torch.rand(2,3)
random_tensor

tensor([[0.2622, 0.9643, 0.3363],
        [0.7104, 0.3358, 0.4379]])

In [16]:
random_tensor.ndim

2

In [17]:
random_tensor.shape

torch.Size([2, 3])

In [18]:
# Create a random tensor with similar shape of an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # heigh, width, colour channels (R, G, B)
random_image_size_tensor

tensor([[[0.4523, 0.9708, 0.7478],
         [0.0447, 0.5368, 0.7535],
         [0.6096, 0.7696, 0.4098],
         ...,
         [0.0604, 0.8969, 0.7067],
         [0.1578, 0.9273, 0.0443],
         [0.1455, 0.6013, 0.5213]],

        [[0.1832, 0.2756, 0.7250],
         [0.4170, 0.8046, 0.5265],
         [0.6209, 0.2857, 0.2009],
         ...,
         [0.4796, 0.9482, 0.1541],
         [0.5940, 0.5609, 0.3326],
         [0.8881, 0.9038, 0.6814]],

        [[0.6740, 0.6211, 0.7696],
         [0.3208, 0.2882, 0.8311],
         [0.0331, 0.0041, 0.2569],
         ...,
         [0.9020, 0.1160, 0.1450],
         [0.2096, 0.2340, 0.0654],
         [0.0450, 0.9390, 0.8683]],

        ...,

        [[0.3087, 0.6876, 0.3338],
         [0.6928, 0.4198, 0.2314],
         [0.2637, 0.2138, 0.2349],
         ...,
         [0.6258, 0.4174, 0.4874],
         [0.8648, 0.3536, 0.0440],
         [0.8048, 0.2647, 0.6355]],

        [[0.0352, 0.6481, 0.3279],
         [0.9990, 0.0559, 0.3184],
         [0.

In [19]:
random_image_size_tensor.ndim

3

In [20]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

### Zeros and Ones

In [21]:
# create a tensor of all zeros
zeros = torch.zeros(size=(2,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# create a tensor with all ones
ones = torch.ones(size=(5,6))
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [24]:
# use torch.range()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
one_to_ten = torch.arange(start=1, end=11, step=2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [26]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor datatype

In [27]:
float_32_tensor = torch.tensor([3.0, 4.5, 5.6],
                               dtype=None,
                               )
float_32_tensor

tensor([3.0000, 4.5000, 5.6000])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_64_tensor = torch.tensor([2.3, 4.9, 9.7],
                               dtype=torch.float64, # what datatype is the tensor(e.g. float64, flaot32, float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_64_tensor

tensor([2.3000, 4.9000, 9.7000], dtype=torch.float64)

In [30]:
# conversion
flaot_16_tensor = float_32_tensor.type(torch.float16)
flaot_16_tensor

tensor([3.0000, 4.5000, 5.6016], dtype=torch.float16)

### Getting information from tensors

In [31]:
X_tensor = torch.rand(3, 5)
X_tensor

tensor([[0.8933, 0.1339, 0.5678, 0.6001, 0.8983],
        [0.3960, 0.1590, 0.9890, 0.5112, 0.8924],
        [0.1811, 0.5238, 0.5384, 0.3086, 0.9237]])

In [32]:
# Find out the details about some tensor
print(f'datatype of tensor: {X_tensor.dtype}')
print(f'Shape of the tensor: {X_tensor.shape}')
print(f'Device on which the tensor is running: {X_tensor.device}')

datatype of tensor: torch.float32
Shape of the tensor: torch.Size([3, 5])
Device on which the tensor is running: cpu


`shape` and `size()` are similar.

In [33]:
X_tensor.size() == X_tensor.shape

True

### Manipulating Tensors (tensors Opertaions)

Tensors Operations:
* Addition
* Substraction
* Multiplication(Element-wise)
* Division
* Matrix Multipication

In [34]:
# Create a tensor and add 101
tensor = torch.tensor([1, 2, 3])
tensor + 101

tensor([102, 103, 104])

In [35]:
torch.add(tensor, 101)

tensor([102, 103, 104])

In [36]:
# Substarct 10 from tensor
tensor - 12

tensor([-11, -10,  -9])

In [37]:
# Multiply tensor by 10\
tensor * 10

tensor([10, 20, 30])

In [38]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [39]:
# divide tensor by 10
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [40]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

### Matrix multiplication

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [41]:
# Element wise multiplication
print(tensor * tensor)

tensor([1, 4, 9])


In [42]:
# Matrix multiplication
print(tensor, '*', tensor)
torch.matmul(tensor, tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])


tensor(14)

In [43]:
X_1 = torch.tensor([[1, 2, 3],
                    [5, 6, 8],
                    [8, 9, 10]])
print(X_1)

Y_1 = torch.tensor([[10, 11, 13],
                    [14, 15, 16],
                    [18, 19, 20]])
print(Y_1)

XY = X_1 * Y_1


tensor([[ 1,  2,  3],
        [ 5,  6,  8],
        [ 8,  9, 10]])
tensor([[10, 11, 13],
        [14, 15, 16],
        [18, 19, 20]])


In [44]:
XY

tensor([[ 10,  22,  39],
        [ 70,  90, 128],
        [144, 171, 200]])

In [45]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 937 µs, sys: 0 ns, total: 937 µs
Wall time: 943 µs


In [46]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 400 µs, sys: 0 ns, total: 400 µs
Wall time: 366 µs


tensor(14)

In [47]:
# @ this is use for matrix multiplication
%%time
torch.rand(3, 4)@torch.rand(4, 5)

CPU times: user 285 µs, sys: 1.05 ms, total: 1.34 ms
Wall time: 1.13 ms


tensor([[0.8413, 1.3802, 1.4117, 1.4408, 1.2529],
        [0.3328, 0.5949, 0.7026, 0.4104, 0.5165],
        [0.8513, 1.4473, 1.4096, 1.0406, 1.1755]])

In [48]:
torch.matmul(torch.rand(1, 5), torch.rand(5, 2)).shape

torch.Size([1, 2])

### One of the most common errors in deep learning: Shape errors

In [49]:
# shape for multiplication
tensor_A = torch.tensor([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]])

tensor_B = torch.tensor([[2, 4, 6],
                         [2, 5, 7],
                         [6, 8, 9]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writting less code)

tensor([[ 24,  38,  47],
        [ 54,  89, 113],
        [ 84, 140, 179]])

In [50]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 3]), torch.Size([3, 3]))

### Rule of multiplication
The **column** of **first matrix** should be **equal** to the `row` of **second matrix**.  
e.g ->
*   `(2, 3)` @ `(2, 3)` -> Can't be multiplied
*   `(2, 3)` @ `(3, 4)` -> will give result matrix of `(2, 4)`

To fix the shape issue we can use **TRANSPOSE** method.



In [51]:
# For Example
tensor_C = torch.rand(1, 2)

tensor_D = torch.rand(1, 2)

tensor_C.shape, tensor_D.shape

(torch.Size([1, 2]), torch.Size([1, 2]))

In [52]:
# if we multiply there two above tensors we will get the error
tensor_C@tensor_D

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x2 and 1x2)

In [53]:
# To fix this error now we gonna use transpose(T)
tensor_D.T.shape # T is use to transope

torch.Size([2, 1])

In [54]:
# Now we got the correct shape for matix multiplcation
tensor_C@tensor_D.T

tensor([[0.6794]])

## Finding the `min`, `max`, `sum`, etc (tensor aggregation)

In [55]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
# finding the min
x.min()

tensor(0)

In [57]:
torch.min(x)

tensor(0)

In [58]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [67]:
# Find the mean
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [68]:
x.dtype

torch.int64

To fix this error we have to change the datatype of the tensor x. because x is int64 which is not allowed for this particular operation

In [69]:
torch.mean(x.type(torch.float64))

tensor(45., dtype=torch.float64)

In [70]:
x.type(torch.float64).mean()

tensor(45., dtype=torch.float64)

In [71]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positonal min and max

In [72]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [73]:
# find the positon in tensor that has minimum value with argmin()
x.argmin()

tensor(0)

In [74]:
# find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)