<a href="https://colab.research.google.com/github/raja-kumar-jha/pytorch-deep-learning-journey/blob/main/notebooks/00_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamantels

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print(torch.__version__)

2.11.0+cpu


## Introduction to tensor
### Creating Tensors

In [2]:
# Scalar
scalar = torch.tensor(27)
scalar

tensor(27)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back to python int
scalar.item()

27

In [5]:
# Vector
vector = torch.tensor([27, 27])
vector

tensor([27, 27])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([3, 3])

In [11]:
# Tensor
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

It is telling that we got **one** `3x3 `**tensor**.






In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

Random number are important because neural network start learning with full of random numbers and then it adjust those numbers to better represent data.



`start with random numbers -> look at data -> update random number -> again look at the data -> again update the data and keep doing until get the result`



In [15]:
# Create the rendom tensor
random_tensor = torch.rand(2,3)
random_tensor

tensor([[0.8803, 0.8854, 0.5318],
        [0.7025, 0.3280, 0.4588]])

In [16]:
random_tensor.ndim

2

In [17]:
random_tensor.shape

torch.Size([2, 3])

In [18]:
# Create a random tensor with similar shape of an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # heigh, width, colour channels (R, G, B)
random_image_size_tensor

tensor([[[0.9728, 0.5512, 0.5428],
         [0.3947, 0.5488, 0.1233],
         [0.5062, 0.0958, 0.4547],
         ...,
         [0.2788, 0.4323, 0.5452],
         [0.6203, 0.6619, 0.2111],
         [0.6089, 0.6383, 0.5127]],

        [[0.8393, 0.9432, 0.5345],
         [0.3376, 0.5345, 0.2115],
         [0.6413, 0.9598, 0.1644],
         ...,
         [0.6483, 0.0558, 0.6911],
         [0.3994, 0.3230, 0.3753],
         [0.9895, 0.8920, 0.6150]],

        [[0.6986, 0.5716, 0.5509],
         [0.7665, 0.2455, 0.9945],
         [0.2402, 0.6597, 0.2446],
         ...,
         [0.3623, 0.6384, 0.9278],
         [0.3467, 0.5880, 0.0033],
         [0.4982, 0.2588, 0.3450]],

        ...,

        [[0.6533, 0.2968, 0.7373],
         [0.1018, 0.4076, 0.3849],
         [0.1532, 0.7490, 0.7329],
         ...,
         [0.8597, 0.4498, 0.9025],
         [0.1812, 0.3710, 0.9317],
         [0.5458, 0.1460, 0.1955]],

        [[0.0438, 0.1307, 0.6911],
         [0.6462, 0.1601, 0.8270],
         [0.

In [19]:
random_image_size_tensor.ndim

3

In [20]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

### Zeros and Ones

In [21]:
# create a tensor of all zeros
zeros = torch.zeros(size=(2,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# create a tensor with all ones
ones = torch.ones(size=(5,6))
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [24]:
# use torch.range()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
one_to_ten = torch.arange(start=1, end=11, step=2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [26]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor datatype

In [27]:
float_32_tensor = torch.tensor([3.0, 4.5, 5.6],
                               dtype=None,
                               )
float_32_tensor

tensor([3.0000, 4.5000, 5.6000])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_64_tensor = torch.tensor([2.3, 4.9, 9.7],
                               dtype=torch.float64, # what datatype is the tensor(e.g. float64, flaot32, float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_64_tensor

tensor([2.3000, 4.9000, 9.7000], dtype=torch.float64)

In [30]:
# conversion
flaot_16_tensor = float_32_tensor.type(torch.float16)
flaot_16_tensor

tensor([3.0000, 4.5000, 5.6016], dtype=torch.float16)

### Getting information from tensors

In [31]:
X_tensor = torch.rand(3, 5)
X_tensor

tensor([[0.7827, 0.3358, 0.5575, 0.9606, 0.7139],
        [0.7040, 0.9601, 0.5301, 0.6086, 0.8919],
        [0.9900, 0.2974, 0.2916, 0.8642, 0.0993]])

In [32]:
# Find out the details about some tensor
print(f'datatype of tensor: {X_tensor.dtype}')
print(f'Shape of the tensor: {X_tensor.shape}')
print(f'Device on which the tensor is running: {X_tensor.device}')

datatype of tensor: torch.float32
Shape of the tensor: torch.Size([3, 5])
Device on which the tensor is running: cpu


`shape` and `size()` are similar.

In [33]:
X_tensor.size() == X_tensor.shape

True

### Manipulating Tensors (tensors Opertaions)

Tensors Operations:
* Addition
* Substraction
* Multiplication(Element-wise)
* Division
* Matrix Multipication

In [34]:
# Create a tensor and add 101
tensor = torch.tensor([1, 2, 3])
tensor + 101

tensor([102, 103, 104])

In [35]:
torch.add(tensor, 101)

tensor([102, 103, 104])

In [36]:
# Substarct 10 from tensor
tensor - 12

tensor([-11, -10,  -9])

In [37]:
# Multiply tensor by 10\
tensor * 10

tensor([10, 20, 30])

In [38]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [39]:
# divide tensor by 10
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [40]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

### Matrix multiplication

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [41]:
# Element wise multiplication
print(tensor * tensor)

tensor([1, 4, 9])


In [42]:
# Matrix multiplication
print(tensor, '*', tensor)
torch.matmul(tensor, tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])


tensor(14)

In [43]:
X_1 = torch.tensor([[1, 2, 3],
                    [5, 6, 8],
                    [8, 9, 10]])
print(X_1)

Y_1 = torch.tensor([[10, 11, 13],
                    [14, 15, 16],
                    [18, 19, 20]])
print(Y_1)

XY = X_1 * Y_1


tensor([[ 1,  2,  3],
        [ 5,  6,  8],
        [ 8,  9, 10]])
tensor([[10, 11, 13],
        [14, 15, 16],
        [18, 19, 20]])


In [44]:
XY

tensor([[ 10,  22,  39],
        [ 70,  90, 128],
        [144, 171, 200]])

In [45]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.87 ms, sys: 0 ns, total: 1.87 ms
Wall time: 2.85 ms


In [46]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 106 µs, sys: 11 µs, total: 117 µs
Wall time: 124 µs


tensor(14)

In [47]:
# @ this is use for matrix multiplication
%%time
torch.rand(3, 4)@torch.rand(4, 5)

CPU times: user 0 ns, sys: 812 µs, total: 812 µs
Wall time: 2.26 ms


tensor([[0.4510, 0.9400, 1.4744, 0.3153, 1.1003],
        [0.5143, 1.1625, 1.5386, 0.1745, 1.4159],
        [0.3051, 0.4769, 0.7838, 0.1410, 0.7120]])

In [48]:
torch.matmul(torch.rand(1, 5), torch.rand(5, 2)).shape

torch.Size([1, 2])

### One of the most common errors in deep learning: Shape errors

In [49]:
# shape for multiplication
tensor_A = torch.tensor([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]])

tensor_B = torch.tensor([[2, 4, 6],
                         [2, 5, 7],
                         [6, 8, 9]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writting less code)

tensor([[ 24,  38,  47],
        [ 54,  89, 113],
        [ 84, 140, 179]])

In [50]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 3]), torch.Size([3, 3]))

### Rule of multiplication
The **column** of **first matrix** should be **equal** to the `row` of **second matrix**.  
e.g ->
*   `(2, 3)` @ `(2, 3)` -> Can't be multiplied
*   `(2, 3)` @ `(3, 4)` -> will give result matrix of `(2, 4)`

To fix the shape issue we can use **TRANSPOSE** method.



In [51]:
# For Example
tensor_C = torch.rand(1, 2)

tensor_D = torch.rand(1, 2)

tensor_C.shape, tensor_D.shape

(torch.Size([1, 2]), torch.Size([1, 2]))

In [53]:
# if we multiply there two above tensors we will get the error
tensor_C@tensor_D

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x2 and 1x2)

In [54]:
# To fix this error now we gonna use transpose(T)
tensor_D.T.shape # T is use to transope

torch.Size([2, 1])

In [55]:
# Now we got the correct shape for matix multiplcation
tensor_C@tensor_D.T

tensor([[0.7481]])

## Finding the `min`, `max`, `sum`, etc (tensor aggregation)

In [56]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
# finding the min
x.min()

tensor(0)

In [58]:
torch.min(x)

tensor(0)

In [59]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [71]:
# Find the mean
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [82]:
x.dtype

torch.int64

To fix this error we have to change the datatype of the tensor x. because x is int64 which is not allowed for this particular operation

In [83]:
torch.mean(x.type(torch.float64))

tensor(45., dtype=torch.float64)

In [84]:
x.type(torch.float64).mean()

tensor(45., dtype=torch.float64)

In [85]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positonal min and max

In [86]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [87]:
# find the positon in tensor that has minimum value with argmin()
x.argmin()

tensor(0)

In [88]:
# find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input to a defind shape
* View - Return a view of an input tensor of certain shape but keep the same memory as original ltensor
* Stacking - combining multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [89]:
# Create a tensor
y = torch.arange(1., 10.)

y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [90]:
# Add an extra dimension
y_reshaped = y.reshape(3, 3)
y_reshaped, y_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [91]:
# Create a view
z = y.view(1, 9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [92]:
# changing z changes y (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 12
z, y

(tensor([[12.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([12.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [93]:
# Stack tensor on top of each other
y_stacked = torch.stack([y, y, y, y], dim=0)
y_stacked

tensor([[12.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [12.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [12.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [12.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [97]:
# torch.squeeze() - removes all the single dimensions from target tensor
y_reshaped

tensor([[12.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]])

In [98]:
y_reshaped.shape

torch.Size([3, 3])

In [99]:
y_reshaped.squeeze()

tensor([[12.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]])

In [108]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [109]:
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [110]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [113]:
y

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [114]:
y = torch.squeeze(x, 0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [115]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [116]:
y = torch.squeeze(x, (1, 2, 3))
y.shape

torch.Size([2, 2, 2])

In [129]:
# torch.unsqueez() - adds a single dimension to a target tensor at a specific dim
A_tensor = torch.arange(1, 10)
A_tensor, A_tensor.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [130]:
A_tensor_squeezed = torch.squeeze(x)
A_tensor_squeezed.shape

torch.Size([2, 2, 2])

In [131]:
A_tensor_squeezed

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [137]:
A_tensor_unsqueezed = A_tensor_squeezed.unsqueeze(dim=1)
A_tensor_unsqueezed.shape

torch.Size([2, 1, 2, 2])

In [138]:
# torch.permute - rearranges the dimensions of target tensor in a spacific order
x_original = torch.rand(size = (224, 224, 3)) # [height, width, and colour_channel]
x_original.shape

torch.Size([224, 224, 3])

In [139]:
# Permute the origin tensor to rearrange the asix (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shift colour_channel to 1st, then height and at the end width [these 2, 0 and 1 is basically the index of it]
x_permuted.shape

torch.Size([3, 224, 224])

In [140]:
x_original[0, 0, 0] = 121
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(121.), tensor(121.))

## Indexing (selecting data from tensors)

In [150]:
# Create a tensor
x = torch.arange(0, 9).reshape(1, 3, 3)
x, x.shape

(tensor([[[0, 1, 2],
          [3, 4, 5],
          [6, 7, 8]]]),
 torch.Size([1, 3, 3]))

In [151]:
# let's index on our new tensor
x[0]

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [153]:
x[0][0], x[0, 0]

(tensor([0, 1, 2]), tensor([0, 1, 2]))

In [157]:
x[0, 1, 1]

tensor(4)

In [158]:
x[0, 2, 2]
# This is our last element

tensor(8)

In [159]:
# we can also use ":" to select all of a target dimension
x[:, 0]

tensor([[0, 1, 2]])

In [161]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[1, 4, 7]])

## PyTorch and NumPy

NumPy is a popular scientific Python numerical computing library. And because of it, PyTorch has functionality to interect with it.

* Data in NumPy -> PyTorch -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> t`orch.tensor.numpy()`


In [162]:
# NumPy array to tensor
array = np.arange(1.0, 10.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [163]:
# tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))